### ISSUE TITLE
Add notes for CSS Flexbox

### ISSUE THREAD

**Issue by yashwin** [yashwin/notes#10]
Please read the instructions before you start working on this issue - https://github.com/yashwin/notes/blob/master/README.md

**Comment by raulcrisan** [comment]
I will start adding notes for css flexbox. Please assign it to me

**Comment by yashwin** [comment]
Done - @raulcrisan

**Comment by yashwin** [comment]
@raulcrisan please have a look at the instructions here - https://github.com/yashwin/notes/blob/master/README.md

**Comment by raulcrisan** [comment]
I've finished it. I have opened a PR
