### ISSUE TITLE
Add notes for CSS Transitions

### ISSUE THREAD

**Issue by yashwin** [yashwin/notes#8]
Please read the instructions before you start working on this issue - https://github.com/yashwin/notes/blob/master/README.md

**Comment by maskott** [comment]
I will add some notes! Anything in particular @yashwin ?

**Comment by yashwin** [comment]
@maskott Please cover all the transition properties which an one line description

**Comment by maskott** [comment]
Done! My Pull Request is here: https://github.com/yashwin/notes/pull/16
