### ISSUE TITLE
Add notes for CSS Animations

### ISSUE THREAD

**Issue by yashwin** [yashwin/notes#9]
Please read the instructions before you start working on this issue - https://github.com/yashwin/notes/blob/master/README.md

**Comment by Lumary2** [comment]
I would like to work on this. :)

**Comment by yashwin** [comment]
Go ahead, @Lumary2

**Comment by yashwin** [comment]
@Lumary2  please have a look at the instructions here https://github.com/yashwin/notes/blob/master/README.md
